#!/bin/sh
# Wrapper de l'intégration DeepSeek pour Wazuh
# L'Integrator de Wazuh exécute ce script ; il relaie les arguments
# au script Python qui contient la logique d'enrichissement.

WPYTHON_BIN="framework/python/bin/python3"

SCRIPT_PATH_NAME="$0"
DIR_NAME="$(cd $(dirname ${SCRIPT_PATH_NAME}); pwd -P)"
SCRIPT_NAME="$(basename ${SCRIPT_PATH_NAME})"

case ${DIR_NAME} in
    */active-response/bin | */wodles*)
        if [ -z "${WAZUH_PATH}" ]; then
            WAZUH_PATH="$(cd ${DIR_NAME}/../..; pwd)"
        fi
        PYTHON_BIN="${WAZUH_PATH}/${WPYTHON_BIN}"
    ;;
    */bin)
        if [ -z "${WAZUH_PATH}" ]; then
            WAZUH_PATH="$(cd ${DIR_NAME}/..; pwd)"
        fi
        PYTHON_BIN="${WAZUH_PATH}/${WPYTHON_BIN}"
    ;;
    */integrations)
        if [ -z "${WAZUH_PATH}" ]; then
            WAZUH_PATH="$(cd ${DIR_NAME}/..; pwd)"
        fi
        PYTHON_BIN="${WAZUH_PATH}/${WPYTHON_BIN}"
    ;;
esac

# Repli : si le Python embarqué de Wazuh n'est pas trouvé, on utilise python3 du système
if [ ! -f "${PYTHON_BIN}" ]; then
    PYTHON_BIN="python3"
fi

${PYTHON_BIN} ${DIR_NAME}/${SCRIPT_NAME}.py "$@"
